name: cypress
on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npx vite --host
          wait-on: 'http://localhost:5173'
        env:
          VITE_DRIFTDB_URL: ${{ vars.DRIFTDB_URL }}

      - name: Record failed screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Record videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
